CREATE TABLE GAMES
(
  GAME_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  GAME_CREATED DATETIME NOT NULL,
  GAME_FINISHED DATETIME,
  CREATED_BY_PLAYER_ID BIGINT,
  gameStatus VARCHAR(255),
  GAME_NAME VARCHAR(255) NOT NULL,
  GAME_STARTED DATETIME
);

CREATE TABLE GAME_PLAYERS_CON
(
  GAME_PLAYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  actionStatus VARCHAR(255),
  IS_CURRENT_PLAYER_TURN TINYINT,
  GAME_ID BIGINT,
  gamePlayerStatus VARCHAR(255),
  NEXT_GAME_PLAYER_ID BIGINT,
  PLAYER_ID BIGINT
);

CREATE TABLE PLAYER
(
  PLAYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL VARCHAR(255),
  PLAYER_NAME VARCHAR(255)
);

CREATE TABLE PLAYER_FRIEND
(
  playerFriendId BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  friendStatus VARCHAR(255),
  friendId BIGINT,
  playerId BIGINT
);

CREATE TABLE UNITS
(
  unitId INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  strength INT NOT NULL,
  territory VARCHAR(255),
  typeOfUnit VARCHAR(255),
  gamePlayerId BIGINT
);

ALTER TABLE GAME_PLAYERS_CON ADD FOREIGN KEY ( PLAYER_ID ) REFERENCES PLAYER ( PLAYER_ID );
ALTER TABLE GAME_PLAYERS_CON ADD FOREIGN KEY ( GAME_ID ) REFERENCES GAMES ( GAME_ID );
CREATE INDEX FK16C4B06826CD65D4 ON GAME_PLAYERS_CON ( GAME_ID );
CREATE INDEX FK16C4B068DC05CF4 ON GAME_PLAYERS_CON ( PLAYER_ID );
CREATE UNIQUE INDEX EMAIL ON PLAYER ( EMAIL );
ALTER TABLE PLAYER_FRIEND ADD FOREIGN KEY ( playerId ) REFERENCES PLAYER ( PLAYER_ID );
ALTER TABLE PLAYER_FRIEND ADD FOREIGN KEY ( friendId ) REFERENCES PLAYER ( PLAYER_ID );
CREATE INDEX FKE7641DBC288365F4 ON PLAYER_FRIEND ( friendId );
CREATE INDEX FKE7641DBCED58F177 ON PLAYER_FRIEND ( playerId );
ALTER TABLE UNITS ADD FOREIGN KEY ( gamePlayerId ) REFERENCES GAME_PLAYERS_CON ( GAME_PLAYER_ID );
CREATE INDEX FK4D25F4FCF1328FB ON UNITS ( gamePlayerId );